#!/bin/bash
#SBATCH --job-name="EQUIL"
#SBATCH --output="/expanse/lustre/projects/iit119/dcooper/MOR/logs/Check.%j.%N.out"
#SBATCH --partition=gpu-shared
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=8G
#SBATCH --account=iit122
#SBATCH -t 6:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=dcooper6@hawk.iit.edu

source ~/.bashrc

conda activate prep

cd $SLURM_SUBMIT_DIR

echo EQUIL BATCH JOB FOR $2
python EQUIL_MEMBRANE.py $1 $2 $3
